# Generated by Django 4.2.5 on 2023-10-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registerstudent_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='rollno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
