# Generated by Django 4.2.5 on 2023-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_registerstudent_firstname_registerstudent_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='section',
            field=models.CharField(choices=[('B', 'B'), ('D', 'D'), ('A', 'A'), ('C', 'C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registerstudent',
            name='stream',
            field=models.CharField(choices=[('Sci', 'Science'), ('Com', 'Commerce'), ('Arts', 'Arts')], max_length=4, null=True),
        ),
    ]
