# Generated by Django 4.2.5 on 2023-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_registerstudent_section_registerstudent_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='section',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('B', 'B'), ('D', 'D')], default='A', max_length=1, null=True),
        ),
    ]
