# Generated by Django 4.2.5 on 2023-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_registerstudent_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='section',
            field=models.CharField(default='A', max_length=1, null=True),
        ),
    ]
