# Generated by Django 4.2.5 on 2023-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_registerstudent_course_coursementormapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='course',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.DeleteModel(
            name='CourseMentorMapping',
        ),
    ]
