# Generated by Django 4.2.5 on 2023-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_registerstudent_course_delete_coursementormapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='rollno',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
    ]
