# Generated by Django 4.2.5 on 2023-10-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_registerstudent_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterStudent',
        ),
    ]
