# Generated by Django 4.2.5 on 2023-10-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_registerstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('primaryEmail', models.EmailField(max_length=254)),
                ('alternateEmail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('rollno', models.PositiveIntegerField()),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('stream', models.CharField(choices=[('Sci', 'Science'), ('Com', 'Commerce'), ('Arts', 'Arts')], max_length=4)),
                ('course', models.CharField(max_length=70, null=True)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
